### ISSUE TITLE
Add Unit Tests for All Methods

### ISSUE THREAD

**Issue by EvanMeyerEmich** [EvanMeyerEmich/emeyer-myMiniCanvas#1]
## User Story
As a developer, I want every method in our codebase to have unit tests, so that we can assure code reliability and functionality.

## Tasks
- Write and implement tests.
- Review test coverage and enhance where necessary.

## Checklist
- [x] Create test_main.py
- [x] Create test_course.py
- [x] Create test_assignment.py
- [x] Create test_user.py
